name: CI

on:
  pull_request:

jobs:
  check_nx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile --prefer-offline
      - uses: nrwl/nx-set-shas@v4

      - name: Show projects to verify Nx
        run: yarn nx show projects
